//! Generate dendro's conceptual diagrams.
//!
//! Run with `docs/regen.sh`, which renders the emitted `.dot` files to SVG.
//! CI fails on any diff against the committed output, so a rename the diagrams
//! claim will either show up renamed or break this program.
//!
//! **Derived, not drawn.** Every node and edge here is checked against the
//! crate's real structures at generation time: the catalog comes from
//! `SCHEMA_SQL` in `db.rs`, the writer's message kinds from its `Msg` enum, the
//! read path's watermark from `LIVE_WAL_PREDICATE`. A claim that stops being
//! true of the source aborts the run rather than rendering a stale picture.

use std::collections::BTreeMap;
use std::path::Path;

const DB_RS: &str = include_str!("../src/db.rs");
const WRITER_RS: &str = include_str!("../src/writer.rs");
const READ_RS: &str = include_str!("../src/read.rs");
const SEGMENT_RS: &str = include_str!("../src/segment.rs");

// ---------------------------------------------------------------------------
// The visual language, shared by every chart in the set.
// ---------------------------------------------------------------------------

/// Operation fills — ColorBrewer Accent, pastel because these are large filled
/// areas a reader looks at for a long time.
mod op {
    pub const INGEST: &str = "#BEAED4";
    pub const TRANSFORM: &str = "#7FC97F";
    pub const DECIDE: &str = "#FFFF99";
    pub const OUTPUT: &str = "#FDC086";
}

/// Data tints — lighter than the operation fills, so data reads as quieter
/// than compute.
mod dat {
    pub const EXTERNAL: &str = "#E6DEF2";
    pub const DERIVED: &str = "#EDEDED";
    pub const DURABLE: &str = "#FBE3CB";
    pub const CONCEPT: &str = "#DDE4CF";
}

const EDGE: &str = "#4D4D4D";
/// The two paths worth separating, in Okabe-Ito colors: rows that are durable
/// but not yet sealed, and rows that have been sealed.
const EDGE_UNSEALED: &str = "#CC79A7";
const EDGE_SEALED: &str = "#D55E00";
const PANEL_FILL: &str = "#F2F2F2";
const PANEL_BORDER: &str = "#9E9E9E";

const FONT: &str = "Helvetica";
const MONO: &str = "Courier";

fn header(title: &str, rankdir: &str) -> String {
    format!(
        "// GENERATED by `cargo run --example gen_diagrams` - do not edit.\n\
         // Source of truth: src/db.rs, src/writer.rs, src/read.rs, src/segment.rs.\n\
         digraph {{\n  \
           label=\"{title}\";\n  \
           labelloc=t;\n  \
           fontname=\"{FONT}\";\n  \
           fontsize=20;\n  \
           rankdir={rankdir};\n  \
           bgcolor=white;\n  \
           node [fontname=\"{FONT}\", fontsize=14, penwidth=1.4, color=\"{EDGE}\"];\n  \
           edge [fontname=\"{FONT}\", fontsize=13, color=\"{EDGE}\", penwidth=1.4];\n"
    )
}

/// A thing that runs. Rounded, always.
fn compute(id: &str, label: &str, fill: &str) -> String {
    format!(
        "  {id} [shape=box, style=\"rounded,filled\", fillcolor=\"{fill}\", label=\"{label}\"];\n"
    )
}

/// A thing that holds. Square, always.
///
/// `dashed` means ONE thing across the whole set: outside dendro. It is not
/// spent on "in memory", or on "has no catalog row" - a channel carrying two
/// meanings is a channel carrying none.
fn data(id: &str, label: &str, fill: &str, outside: bool) -> String {
    let style = if outside { "filled,dashed" } else { "filled" };
    format!("  {id} [shape=box, style=\"{style}\", fillcolor=\"{fill}\", label=\"{label}\"];\n")
}

/// A square holding one value. No segmentation, because there is no history to
/// look back over - a capacity-1 channel holds the current item and nothing else.
fn cell(id: &str, label: &str, fill: &str) -> String {
    format!("  {id} [shape=box, style=filled, fillcolor=\"{fill}\", label=\"{label}\", width=0.45, height=0.45];\n")
}

/// A thing that holds *a history* - segmented, because a reader can look back
/// over it. Never used for something written once.
fn history(id: &str, label: &str, fill: &str) -> String {
    format!("  {id} [shape=record, style=filled, fillcolor=\"{fill}\", label=\"{label}\"];\n")
}

// ---------------------------------------------------------------------------
// Ground truth
// ---------------------------------------------------------------------------

/// The `SCHEMA_SQL` literal, lifted out of `db.rs`.
fn schema_sql() -> &'static str {
    let anchor = "const SCHEMA_SQL: &str = \"";
    let start = DB_RS
        .find(anchor)
        .expect("db.rs no longer defines SCHEMA_SQL - the diagrams describe a schema that is gone")
        + anchor.len();
    let rest = &DB_RS[start..];
    let end = rest
        .find("\";")
        .expect("SCHEMA_SQL literal is unterminated");
    &rest[..end]
}

/// Catalog tables and their columns, parsed from the schema.
fn catalog() -> BTreeMap<String, Vec<String>> {
    let mut out = BTreeMap::new();
    for chunk in schema_sql().split("CREATE TABLE ").skip(1) {
        let (name, rest) = chunk.split_once('(').expect("CREATE TABLE without a body");
        let body = &rest[..rest.find(");").expect("unterminated CREATE TABLE")];
        let cols = body
            .lines()
            .filter_map(|l| {
                let l = l.trim();
                if l.is_empty() || l.starts_with("--") || l.starts_with("PRIMARY KEY") {
                    return None;
                }
                l.split_whitespace().next().map(str::to_string)
            })
            .collect();
        out.insert(name.trim().to_string(), cols);
    }
    out
}

/// Abort unless `haystack` contains `needle`, naming the claim that broke.
fn claim(haystack: &str, needle: &str, what: &str) {
    assert!(
        haystack.contains(needle),
        "the diagrams claim {what}, but `{needle}` is no longer in the source.\n\
         Fix the diagram or the claim - do not delete this assertion."
    );
}

/// Abort on a table the diagrams neither draw nor deliberately omit.
///
/// The same rule `every_schema_table_is_either_copied_or_deliberately_dropped`
/// applies to the rewrite path: silence is the failure mode worth preventing,
/// because a chart missing a table still renders as a complete-looking chart.
fn classify_tables(cat: &BTreeMap<String, Vec<String>>) {
    /// Drawn in the storage column of the model chart.
    const DRAWN: &[&str] = &["sources", "segments", "wal"];
    /// Real, and deliberately not drawn, with the reason.
    const NOT_DRAWN: &[(&str, &str)] = &[
        (
            "clock_offsets",
            "a per-source observation series; it carries no part of the \
             archive -> stream -> segment -> row model the chart is about",
        ),
        (
            "schema_version",
            "one row, written at creation; describes the catalog rather than \
             appearing in it",
        ),
    ];

    for name in cat.keys() {
        let drawn = DRAWN.contains(&name.as_str());
        let omitted = NOT_DRAWN.iter().any(|(t, _)| t == name);
        assert!(
            drawn ^ omitted,
            "catalog table `{name}` is neither drawn nor deliberately omitted \
             (or is listed as both). Add it to DRAWN, or to NOT_DRAWN with the \
             reason it does not belong in the model chart."
        );
    }
    for t in DRAWN.iter().chain(NOT_DRAWN.iter().map(|(t, _)| t)) {
        assert!(
            cat.contains_key(*t),
            "the diagrams classify a table `{t}` the schema no longer has"
        );
    }
}

// ---------------------------------------------------------------------------
// Chart 1 - the model
// ---------------------------------------------------------------------------

/// What nests, and what is only a shared key.
///
/// The claim a reader most often gets wrong is that a **stream is not a row in
/// the catalog**. It has no table: it is a name that rows in `segments` and
/// `wal` carry, and the reader is what gathers them. Outline style is spent on
/// exactly that distinction.
fn model(cat: &BTreeMap<String, Vec<String>>) -> String {
    classify_tables(cat);

    // The chart draws these columns; if they are renamed it has to change.
    for (table, col) in [
        ("sources", "labels"),
        ("sources", "clock_anchor_wall_ns"),
        ("segments", "stream"),
        ("segments", "seq"),
        ("segments", "bytes"),
        ("wal", "stream"),
        ("wal", "ts"),
        ("wal", "row"),
    ] {
        assert!(
            cat[table].iter().any(|c| c == col),
            "the model chart draws `{table}.{col}`, which the schema no longer has"
        );
    }

    let mut s = header("dendro: the model", "TB");
    s.push_str("  compound=true;\n  nodesep=0.45;\n  ranksep=0.6;\n");

    // -- the archive IS the cluster. Drawing it as a node beside its own
    //    contents would put the file at the same level as the things inside it.
    s.push_str(&format!(
        "  subgraph cluster_archive {{\n    \
           label=\"archive - one file\";\n    fontsize=16;\n    labeljust=l;\n    \
           style=filled;\n    fillcolor=\"#FAFAFA\";\n    color=\"{PANEL_BORDER}\";\n"
    ));
    s.push_str(&data(
        "source",
        "source\\none producer, one clock domain,\\none label set",
        dat::EXTERNAL,
        false,
    ));
    // Unfilled, and that is the claim: nothing stores a stream. Absence has to
    // be legible, or the reader reads it as merely unmarked.
    s.push_str(
        "    stream [shape=box, style=solid, fillcolor=white, \
           label=\"stream\\na named sequence of rows\\n(no table of its own)\"];\n",
    );
    s.push_str(&history(
        "segments",
        "segment|segment|segment|...",
        dat::DURABLE,
    ));
    s.push_str(&data(
        "row",
        "row\\ntimestamp + opaque bytes",
        dat::DERIVED,
        false,
    ));
    s.push_str(
        "    source -> stream [label=\"names\"];\n    \
             stream -> segments [label=\"is, end to end\"];\n    \
             segments -> row [label=\"holds\"];\n  }\n",
    );

    // -- how it is actually stored ------------------------------------------
    s.push_str(&format!(
        "  subgraph cluster_catalog {{\n    \
           label=\"the catalog (SQLite), inside that same file\";\n    fontsize=16;\n    labeljust=l;\n    \
           style=filled;\n    fillcolor=\"{PANEL_FILL}\";\n    color=\"{PANEL_BORDER}\";\n"
    ));
    s.push_str(&format!(
        "    t_sources [shape=box, style=filled, fillcolor=\"{}\", \
           fontname=\"{MONO}\", label=\"sources\\lid, labels, metadata,\\lcomplete, clock_anchor_wall_ns\\l\"];\n",
        dat::EXTERNAL
    ));
    s.push_str(&format!(
        "    t_segments [shape=box, style=filled, fillcolor=\"{}\", \
           fontname=\"{MONO}\", label=\"segments\\lsource_id, stream, seq,\\lrows, first_ts, last_ts, bytes\\l\"];\n",
        dat::DURABLE
    ));
    s.push_str(&format!(
        "    t_wal [shape=box, style=filled, fillcolor=\"{}\", \
           fontname=\"{MONO}\", label=\"wal\\lsource_id, stream, ts,\\lwall_offset, row\\l\"];\n",
        dat::DERIVED
    ));
    s.push_str("  }\n");

    s.push_str(&format!(
        "  source -> t_sources [style=dotted, label=\"one row\", color=\"{EDGE}\"];\n  \
           segments -> t_segments [style=dotted, color=\"{EDGE_SEALED}\", \
             label=\"one row each,\\lparquet in `bytes`\\l\"];\n  \
           row -> t_wal [style=dotted, color=\"{EDGE_UNSEALED}\", \
             label=\"one row each,\\luntil it is sealed\\l\"];\n"
    ));
    s.push_str(&format!(
        "  stream -> t_segments [style=dotted, color=\"{EDGE}\", \
           label=\"just a column -\\lin `segments` and in `wal`,\\lgathered on read\\l\"];\n"
    ));

    s.push_str(&key_model());
    s.push_str("}\n");
    s
}

/// The key for the model chart.
///
/// `rank=same` lays this out as one horizontal band in a `rankdir=TB` graph.
/// Chained on invisible edges it spreads over the main graph's ranks instead,
/// which are tall, and the gaps between entries read as meaningful.
///
/// The dotted channel is shown as a border for the same reason the path charts
/// show their edge colors that way: a sample edge inside a `rank=same` cluster
/// renders along the wrong axis.
fn key_model() -> String {
    let mut s = format!(
        "  subgraph cluster_key {{\n    label=\"key\";\n    fontsize=13;\n    labeljust=l;\n    \
           style=filled;\n    fillcolor=\"{PANEL_FILL}\";\n    color=\"{PANEL_BORDER}\";\n    \
           node [fontsize=11, height=0.32];\n    rank=same;\n"
    );
    s.push_str(
        "    k_none [shape=box, style=solid, fillcolor=white, \
           label=\"unfilled: nothing\\lstores it\\l\"];\n",
    );
    s.push_str(&format!(
        "    k_fill [shape=box, style=filled, fillcolor=\"{}\", \
           label=\"filled: the tint names\\lthe table that stores it\\l\"];\n",
        dat::DURABLE
    ));
    s.push_str(&format!(
        "    k_hist [shape=record, style=filled, fillcolor=\"{}\", \
           label=\"segmented: a history\"];\n",
        dat::DURABLE
    ));
    s.push_str(&format!(
        "    k_map [shape=box, style=\"filled,dotted\", fillcolor=\"{PANEL_FILL}\", \
           penwidth=2, label=\"dotted: stored as\"];\n"
    ));
    s.push_str("  }\n");
    s
}

// ---------------------------------------------------------------------------
// Chart 2 - the write path
// ---------------------------------------------------------------------------

/// One row, from the caller's append to a sealed segment.
fn write_path(cat: &BTreeMap<String, Vec<String>>) -> String {
    claim(
        WRITER_RS,
        "Wal { ticks",
        "the writer takes appends as a `Wal` message",
    );
    claim(
        WRITER_RS,
        "Seal { source_id",
        "the writer takes seals as a `Seal` message",
    );
    claim(
        WRITER_RS,
        "sync_channel(1)",
        "the hand-off channel is bounded at 1",
    );
    claim(
        WRITER_RS,
        ".encode(&stream, &rows)",
        "sealing calls the caller's encoder",
    );
    claim(
        WRITER_RS,
        "db.prune_wal(",
        "sealing prunes the WAL it just sealed",
    );
    claim(SEGMENT_RS, "trait SegmentEncoder", "the encoder is a trait");
    assert!(
        cat.contains_key("wal"),
        "the write path draws the `wal` table"
    );

    let mut s = header("dendro: the write path", "LR");
    s.push_str("  nodesep=0.4;\n  ranksep=0.75;\n");

    s.push_str(&data("caller", "caller", dat::EXTERNAL, true));
    s.push_str(&compute(
        "append",
        "1. append\\n`SourceWriter::wal`",
        op::INGEST,
    ));
    // One cell: the channel is bounded at 1, so there is no history to segment.
    // A two-celled glyph here would promise a depth the hand-off does not have.
    s.push_str(&cell("chan", "hand-off\\ncapacity 1", dat::DERIVED));
    s.push_str(&compute(
        "commit",
        "2. commit\\none transaction,\\none fsync",
        op::TRANSFORM,
    ));
    s.push_str(&history("wal", "row|row|row|...", dat::DERIVED));
    s.push_str(&compute(
        "due",
        "3. is this segment due?\\n`seal::SealPolicy`",
        op::DECIDE,
    ));
    s.push_str(&compute(
        "encode",
        "4. encode\\n`SegmentEncoder`",
        op::OUTPUT,
    ));
    s.push_str(&data(
        "segment",
        "segment\\nparquet bytes",
        dat::DURABLE,
        false,
    ));
    s.push_str(&compute(
        "prune",
        "5. prune\\nup to the sealed `last_ts`",
        op::TRANSFORM,
    ));

    s.push_str(&format!(
        "  caller -> append [style=dashed];\n  \
           append -> chan [label=\"rows\"];\n  \
           chan -> commit [label=\"blocks while the\\lwriter is busy\\l\"];\n  \
           commit -> wal [color=\"{EDGE_UNSEALED}\", penwidth=2, \
             label=\"durable, and\\lreadable now\\l\"];\n  \
           wal -> due [style=dotted, label=\"rows, bytes, age\"];\n  \
           due -> encode [label=\"yes\"];\n  \
           wal -> encode [color=\"{EDGE_UNSEALED}\", label=\"this stream's\\llive rows\\l\"];\n  \
           encode -> segment [color=\"{EDGE_SEALED}\", penwidth=2];\n  \
           segment -> prune [style=dotted];\n  \
           prune -> wal [style=dashed, constraint=false, \
             label=\"only this stream,\\lonly up to `last_ts`\\l\"];\n"
    ));

    // The boundary is the whole point of the chart, so draw it.
    s.push_str(&format!(
        "  subgraph cluster_yours {{\n    label=\"yours\";\n    fontsize=14;\n    labeljust=l;\n    \
           style=dashed;\n    color=\"{PANEL_BORDER}\";\n    encode;\n  }}\n"
    ));

    s.push_str(&key_paths());
    s.push_str("}\n");
    s
}

// ---------------------------------------------------------------------------
// Chart 3 - the read path
// ---------------------------------------------------------------------------

/// Why an archive reads correctly while someone else is still writing it.
fn read_path() -> String {
    claim(
        DB_RS,
        "const LIVE_WAL_PREDICATE",
        "the watermark is one shared predicate",
    );
    claim(
        DB_RS,
        "ts > COALESCE(",
        "the watermark is a `ts >` comparison",
    );
    claim(
        READ_RS,
        "encoder.encode(stream, &db.live_wal(",
        "the tail is materialized through the encoder",
    );
    claim(
        READ_RS,
        "segments.push(tail.bytes)",
        "the tail is appended as the newest segment",
    );
    claim(
        READ_RS,
        "pub fn read_archive",
        "the entry point is `read_archive`",
    );

    let mut s = header("dendro: the read path", "LR");
    s.push_str("  nodesep=0.4;\n  ranksep=0.75;\n");

    s.push_str(&history("sealed", "seq 0|seq 1|seq 2", dat::DURABLE));
    s.push_str(&history("live", "row|row", dat::DERIVED));
    s.push_str(&compute(
        "watermark",
        "1. select live rows\\n`ts > MAX(last_ts)`\\nfor this stream, this source",
        op::DECIDE,
    ));
    s.push_str(&compute(
        "materialize",
        "2. materialize the tail\\n`SegmentEncoder`",
        op::OUTPUT,
    ));
    s.push_str(&data(
        "tail",
        "tail\\nparquet bytes, in memory -\\nnever written to the archive",
        dat::DERIVED,
        false,
    ));
    s.push_str(&compute(
        "splice",
        "3. splice\\noldest first, tail last",
        op::TRANSFORM,
    ));
    s.push_str(&data(
        "bytes",
        "parquet bytes\\nopen with any reader",
        dat::CONCEPT,
        false,
    ));

    s.push_str(&format!(
        "  live -> watermark [color=\"{EDGE_UNSEALED}\"];\n  \
           sealed -> watermark [style=dotted, label=\"MAX(last_ts)\"];\n  \
           watermark -> materialize [color=\"{EDGE_UNSEALED}\", \
             label=\"rows past\\lthe watermark\\l\"];\n  \
           materialize -> tail [color=\"{EDGE_UNSEALED}\"];\n  \
           sealed -> splice [color=\"{EDGE_SEALED}\", penwidth=2];\n  \
           tail -> splice [color=\"{EDGE_UNSEALED}\", penwidth=2];\n  \
           splice -> bytes [penwidth=2];\n"
    ));
    s.push_str(&format!(
        "  subgraph cluster_yours {{\n    label=\"yours\";\n    fontsize=14;\n    labeljust=l;\n    \
           style=dashed;\n    color=\"{PANEL_BORDER}\";\n    materialize;\n  }}\n"
    ));

    s.push_str(&key_paths());
    s.push_str("}\n");
    s
}

/// The key for the path charts.
///
/// `rank=same` is what stacks it: these charts are `rankdir=LR`, where an
/// invisible chain would lay the key out horizontally across the full width and
/// it would read as a second diagram rather than a legend.
fn key_paths() -> String {
    let mut s = format!(
        "  subgraph cluster_key {{\n    label=\"key\";\n    fontsize=13;\n    labeljust=l;\n    \
           style=filled;\n    fillcolor=\"{PANEL_FILL}\";\n    color=\"{PANEL_BORDER}\";\n    \
           node [fontsize=11, height=0.3];\n    rank=same;\n"
    );
    // Emitted in reverse: `rank=same` lays a cluster out bottom-to-top in an
    // LR graph, so this is what puts the shape channel at the top, where a
    // reader looking up a mark starts.
    //
    // The two edge colors are shown as a border rather than as a sample edge.
    // A real edge between two points inside a `rank=same` cluster renders
    // VERTICALLY in an LR graph, which reads as a different channel from the
    // horizontal edges it is supposed to explain. A border is still the color
    // itself rather than its name, which is the property that matters.
    s.push_str(&format!(
        "    k_sealed [shape=box, style=filled, fillcolor=\"{PANEL_FILL}\", \
           color=\"{EDGE_SEALED}\", penwidth=3, label=\"sealed\"];\n    \
             k_unsealed [shape=box, style=filled, fillcolor=\"{PANEL_FILL}\", \
           color=\"{EDGE_UNSEALED}\", penwidth=3, label=\"unsealed\"];\n"
    ));
    s.push_str(&format!(
        "    k_ext [shape=box, style=\"filled,dashed\", fillcolor=\"{}\", \
           label=\"dashed: outside dendro\"];\n",
        dat::EXTERNAL
    ));
    s.push_str(&format!(
        "    k_hist [shape=record, style=filled, fillcolor=\"{}\", \
           label=\"segmented: a history\"];\n",
        dat::DERIVED
    ));
    s.push_str(&format!(
        "    k_dat [shape=box, style=filled, fillcolor=\"{}\", \
           label=\"square: holds\"];\n",
        dat::DURABLE
    ));
    s.push_str(&format!(
        "    k_op [shape=box, style=\"rounded,filled\", fillcolor=\"{}\", \
           label=\"rounded: runs\"];\n",
        op::TRANSFORM
    ));
    s.push_str("  }\n");
    s
}

// ---------------------------------------------------------------------------

fn main() {
    let out = Path::new(env!("CARGO_MANIFEST_DIR")).join("docs");
    std::fs::create_dir_all(&out).expect("create docs/");
    let cat = catalog();

    let charts: [(&str, String); 3] = [
        ("model.dot", model(&cat)),
        ("write-path.dot", write_path(&cat)),
        ("read-path.dot", read_path()),
    ];
    for (name, body) in charts {
        std::fs::write(out.join(name), &body).unwrap_or_else(|e| panic!("write {name}: {e}"));
        println!("wrote docs/{name} ({} bytes)", body.len());
    }
}
